package com.system.po;

import java.util.Date;

public class employee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.id
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.ORG_ID
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    private Integer orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.CLIENT_ID
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    private Integer clientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.username
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.gender
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.phone
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.id_card
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.birthday
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.hire_date
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    private Date hireDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.resign_date
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    private Date resignDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.imgset_dir
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    private String imgsetDir;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.profile_photo
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    private String profilePhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.DESCRIPTION
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.ISACTIVE
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    private String isactive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.CREATED
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.CREATEBY
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    private Integer createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.UPDATED
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    private Date updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.UPDATEBY
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    private Integer updateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.REMOVE
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    private String remove;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.id
     *
     * @return the value of employee_info.id
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.id
     *
     * @param id the value for employee_info.id
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.ORG_ID
     *
     * @return the value of employee_info.ORG_ID
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.ORG_ID
     *
     * @param orgId the value for employee_info.ORG_ID
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.CLIENT_ID
     *
     * @return the value of employee_info.CLIENT_ID
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    public Integer getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.CLIENT_ID
     *
     * @param clientId the value for employee_info.CLIENT_ID
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.username
     *
     * @return the value of employee_info.username
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.username
     *
     * @param username the value for employee_info.username
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.gender
     *
     * @return the value of employee_info.gender
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.gender
     *
     * @param gender the value for employee_info.gender
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.phone
     *
     * @return the value of employee_info.phone
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.phone
     *
     * @param phone the value for employee_info.phone
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.id_card
     *
     * @return the value of employee_info.id_card
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.id_card
     *
     * @param idCard the value for employee_info.id_card
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.birthday
     *
     * @return the value of employee_info.birthday
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.birthday
     *
     * @param birthday the value for employee_info.birthday
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.hire_date
     *
     * @return the value of employee_info.hire_date
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    public Date getHireDate() {
        return hireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.hire_date
     *
     * @param hireDate the value for employee_info.hire_date
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    public void setHireDate(Date hireDate) {
        this.hireDate = hireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.resign_date
     *
     * @return the value of employee_info.resign_date
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    public Date getResignDate() {
        return resignDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.resign_date
     *
     * @param resignDate the value for employee_info.resign_date
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    public void setResignDate(Date resignDate) {
        this.resignDate = resignDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.imgset_dir
     *
     * @return the value of employee_info.imgset_dir
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    public String getImgsetDir() {
        return imgsetDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.imgset_dir
     *
     * @param imgsetDir the value for employee_info.imgset_dir
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    public void setImgsetDir(String imgsetDir) {
        this.imgsetDir = imgsetDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.profile_photo
     *
     * @return the value of employee_info.profile_photo
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    public String getProfilePhoto() {
        return profilePhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.profile_photo
     *
     * @param profilePhoto the value for employee_info.profile_photo
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    public void setProfilePhoto(String profilePhoto) {
        this.profilePhoto = profilePhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.DESCRIPTION
     *
     * @return the value of employee_info.DESCRIPTION
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.DESCRIPTION
     *
     * @param description the value for employee_info.DESCRIPTION
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.ISACTIVE
     *
     * @return the value of employee_info.ISACTIVE
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    public String getIsactive() {
        return isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.ISACTIVE
     *
     * @param isactive the value for employee_info.ISACTIVE
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    public void setIsactive(String isactive) {
        this.isactive = isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.CREATED
     *
     * @return the value of employee_info.CREATED
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.CREATED
     *
     * @param created the value for employee_info.CREATED
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.CREATEBY
     *
     * @return the value of employee_info.CREATEBY
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    public Integer getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.CREATEBY
     *
     * @param createby the value for employee_info.CREATEBY
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    public void setCreateby(Integer createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.UPDATED
     *
     * @return the value of employee_info.UPDATED
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.UPDATED
     *
     * @param updated the value for employee_info.UPDATED
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.UPDATEBY
     *
     * @return the value of employee_info.UPDATEBY
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    public Integer getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.UPDATEBY
     *
     * @param updateby the value for employee_info.UPDATEBY
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    public void setUpdateby(Integer updateby) {
        this.updateby = updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.REMOVE
     *
     * @return the value of employee_info.REMOVE
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    public String getRemove() {
        return remove;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.REMOVE
     *
     * @param remove the value for employee_info.REMOVE
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    public void setRemove(String remove) {
        this.remove = remove;
    }
}