package com.system.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class eventExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table event_info
     *
     * @mbggenerated Mon Jul 06 15:40:52 GMT+08:00 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table event_info
     *
     * @mbggenerated Mon Jul 06 15:40:52 GMT+08:00 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table event_info
     *
     * @mbggenerated Mon Jul 06 15:40:52 GMT+08:00 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_info
     *
     * @mbggenerated Mon Jul 06 15:40:52 GMT+08:00 2020
     */
    public eventExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_info
     *
     * @mbggenerated Mon Jul 06 15:40:52 GMT+08:00 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_info
     *
     * @mbggenerated Mon Jul 06 15:40:52 GMT+08:00 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_info
     *
     * @mbggenerated Mon Jul 06 15:40:52 GMT+08:00 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_info
     *
     * @mbggenerated Mon Jul 06 15:40:52 GMT+08:00 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_info
     *
     * @mbggenerated Mon Jul 06 15:40:52 GMT+08:00 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_info
     *
     * @mbggenerated Mon Jul 06 15:40:52 GMT+08:00 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_info
     *
     * @mbggenerated Mon Jul 06 15:40:52 GMT+08:00 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_info
     *
     * @mbggenerated Mon Jul 06 15:40:52 GMT+08:00 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_info
     *
     * @mbggenerated Mon Jul 06 15:40:52 GMT+08:00 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_info
     *
     * @mbggenerated Mon Jul 06 15:40:52 GMT+08:00 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table event_info
     *
     * @mbggenerated Mon Jul 06 15:40:52 GMT+08:00 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andEventTypeIsNull() {
            addCriterion("event_type is null");
            return (Criteria) this;
        }

        public Criteria andEventTypeIsNotNull() {
            addCriterion("event_type is not null");
            return (Criteria) this;
        }

        public Criteria andEventTypeEqualTo(Integer value) {
            addCriterion("event_type =", value, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeNotEqualTo(Integer value) {
            addCriterion("event_type <>", value, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeGreaterThan(Integer value) {
            addCriterion("event_type >", value, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("event_type >=", value, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeLessThan(Integer value) {
            addCriterion("event_type <", value, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeLessThanOrEqualTo(Integer value) {
            addCriterion("event_type <=", value, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeIn(List<Integer> values) {
            addCriterion("event_type in", values, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeNotIn(List<Integer> values) {
            addCriterion("event_type not in", values, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeBetween(Integer value1, Integer value2) {
            addCriterion("event_type between", value1, value2, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("event_type not between", value1, value2, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventDateIsNull() {
            addCriterion("event_date is null");
            return (Criteria) this;
        }

        public Criteria andEventDateIsNotNull() {
            addCriterion("event_date is not null");
            return (Criteria) this;
        }

        public Criteria andEventDateEqualTo(Date value) {
            addCriterion("event_date =", value, "eventDate");
            return (Criteria) this;
        }

        public Criteria andEventDateNotEqualTo(Date value) {
            addCriterion("event_date <>", value, "eventDate");
            return (Criteria) this;
        }

        public Criteria andEventDateGreaterThan(Date value) {
            addCriterion("event_date >", value, "eventDate");
            return (Criteria) this;
        }

        public Criteria andEventDateGreaterThanOrEqualTo(Date value) {
            addCriterion("event_date >=", value, "eventDate");
            return (Criteria) this;
        }

        public Criteria andEventDateLessThan(Date value) {
            addCriterion("event_date <", value, "eventDate");
            return (Criteria) this;
        }

        public Criteria andEventDateLessThanOrEqualTo(Date value) {
            addCriterion("event_date <=", value, "eventDate");
            return (Criteria) this;
        }

        public Criteria andEventDateIn(List<Date> values) {
            addCriterion("event_date in", values, "eventDate");
            return (Criteria) this;
        }

        public Criteria andEventDateNotIn(List<Date> values) {
            addCriterion("event_date not in", values, "eventDate");
            return (Criteria) this;
        }

        public Criteria andEventDateBetween(Date value1, Date value2) {
            addCriterion("event_date between", value1, value2, "eventDate");
            return (Criteria) this;
        }

        public Criteria andEventDateNotBetween(Date value1, Date value2) {
            addCriterion("event_date not between", value1, value2, "eventDate");
            return (Criteria) this;
        }

        public Criteria andEventLocationIsNull() {
            addCriterion("event_location is null");
            return (Criteria) this;
        }

        public Criteria andEventLocationIsNotNull() {
            addCriterion("event_location is not null");
            return (Criteria) this;
        }

        public Criteria andEventLocationEqualTo(String value) {
            addCriterion("event_location =", value, "eventLocation");
            return (Criteria) this;
        }

        public Criteria andEventLocationNotEqualTo(String value) {
            addCriterion("event_location <>", value, "eventLocation");
            return (Criteria) this;
        }

        public Criteria andEventLocationGreaterThan(String value) {
            addCriterion("event_location >", value, "eventLocation");
            return (Criteria) this;
        }

        public Criteria andEventLocationGreaterThanOrEqualTo(String value) {
            addCriterion("event_location >=", value, "eventLocation");
            return (Criteria) this;
        }

        public Criteria andEventLocationLessThan(String value) {
            addCriterion("event_location <", value, "eventLocation");
            return (Criteria) this;
        }

        public Criteria andEventLocationLessThanOrEqualTo(String value) {
            addCriterion("event_location <=", value, "eventLocation");
            return (Criteria) this;
        }

        public Criteria andEventLocationLike(String value) {
            addCriterion("event_location like", value, "eventLocation");
            return (Criteria) this;
        }

        public Criteria andEventLocationNotLike(String value) {
            addCriterion("event_location not like", value, "eventLocation");
            return (Criteria) this;
        }

        public Criteria andEventLocationIn(List<String> values) {
            addCriterion("event_location in", values, "eventLocation");
            return (Criteria) this;
        }

        public Criteria andEventLocationNotIn(List<String> values) {
            addCriterion("event_location not in", values, "eventLocation");
            return (Criteria) this;
        }

        public Criteria andEventLocationBetween(String value1, String value2) {
            addCriterion("event_location between", value1, value2, "eventLocation");
            return (Criteria) this;
        }

        public Criteria andEventLocationNotBetween(String value1, String value2) {
            addCriterion("event_location not between", value1, value2, "eventLocation");
            return (Criteria) this;
        }

        public Criteria andEventDescIsNull() {
            addCriterion("event_desc is null");
            return (Criteria) this;
        }

        public Criteria andEventDescIsNotNull() {
            addCriterion("event_desc is not null");
            return (Criteria) this;
        }

        public Criteria andEventDescEqualTo(String value) {
            addCriterion("event_desc =", value, "eventDesc");
            return (Criteria) this;
        }

        public Criteria andEventDescNotEqualTo(String value) {
            addCriterion("event_desc <>", value, "eventDesc");
            return (Criteria) this;
        }

        public Criteria andEventDescGreaterThan(String value) {
            addCriterion("event_desc >", value, "eventDesc");
            return (Criteria) this;
        }

        public Criteria andEventDescGreaterThanOrEqualTo(String value) {
            addCriterion("event_desc >=", value, "eventDesc");
            return (Criteria) this;
        }

        public Criteria andEventDescLessThan(String value) {
            addCriterion("event_desc <", value, "eventDesc");
            return (Criteria) this;
        }

        public Criteria andEventDescLessThanOrEqualTo(String value) {
            addCriterion("event_desc <=", value, "eventDesc");
            return (Criteria) this;
        }

        public Criteria andEventDescLike(String value) {
            addCriterion("event_desc like", value, "eventDesc");
            return (Criteria) this;
        }

        public Criteria andEventDescNotLike(String value) {
            addCriterion("event_desc not like", value, "eventDesc");
            return (Criteria) this;
        }

        public Criteria andEventDescIn(List<String> values) {
            addCriterion("event_desc in", values, "eventDesc");
            return (Criteria) this;
        }

        public Criteria andEventDescNotIn(List<String> values) {
            addCriterion("event_desc not in", values, "eventDesc");
            return (Criteria) this;
        }

        public Criteria andEventDescBetween(String value1, String value2) {
            addCriterion("event_desc between", value1, value2, "eventDesc");
            return (Criteria) this;
        }

        public Criteria andEventDescNotBetween(String value1, String value2) {
            addCriterion("event_desc not between", value1, value2, "eventDesc");
            return (Criteria) this;
        }

        public Criteria andOldpersonIdIsNull() {
            addCriterion("oldperson_id is null");
            return (Criteria) this;
        }

        public Criteria andOldpersonIdIsNotNull() {
            addCriterion("oldperson_id is not null");
            return (Criteria) this;
        }

        public Criteria andOldpersonIdEqualTo(Integer value) {
            addCriterion("oldperson_id =", value, "oldpersonId");
            return (Criteria) this;
        }

        public Criteria andOldpersonIdNotEqualTo(Integer value) {
            addCriterion("oldperson_id <>", value, "oldpersonId");
            return (Criteria) this;
        }

        public Criteria andOldpersonIdGreaterThan(Integer value) {
            addCriterion("oldperson_id >", value, "oldpersonId");
            return (Criteria) this;
        }

        public Criteria andOldpersonIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("oldperson_id >=", value, "oldpersonId");
            return (Criteria) this;
        }

        public Criteria andOldpersonIdLessThan(Integer value) {
            addCriterion("oldperson_id <", value, "oldpersonId");
            return (Criteria) this;
        }

        public Criteria andOldpersonIdLessThanOrEqualTo(Integer value) {
            addCriterion("oldperson_id <=", value, "oldpersonId");
            return (Criteria) this;
        }

        public Criteria andOldpersonIdIn(List<Integer> values) {
            addCriterion("oldperson_id in", values, "oldpersonId");
            return (Criteria) this;
        }

        public Criteria andOldpersonIdNotIn(List<Integer> values) {
            addCriterion("oldperson_id not in", values, "oldpersonId");
            return (Criteria) this;
        }

        public Criteria andOldpersonIdBetween(Integer value1, Integer value2) {
            addCriterion("oldperson_id between", value1, value2, "oldpersonId");
            return (Criteria) this;
        }

        public Criteria andOldpersonIdNotBetween(Integer value1, Integer value2) {
            addCriterion("oldperson_id not between", value1, value2, "oldpersonId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table event_info
     *
     * @mbggenerated do_not_delete_during_merge Mon Jul 06 15:40:52 GMT+08:00 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table event_info
     *
     * @mbggenerated Mon Jul 06 15:40:52 GMT+08:00 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}