package com.system.po;

import java.util.Date;

public class event {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_info.id
     *
     * @mbggenerated Mon Jul 06 15:40:52 GMT+08:00 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_info.event_type
     *
     * @mbggenerated Mon Jul 06 15:40:52 GMT+08:00 2020
     */
    private Integer eventType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_info.event_date
     *
     * @mbggenerated Mon Jul 06 15:40:52 GMT+08:00 2020
     */
    private Date eventDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_info.event_location
     *
     * @mbggenerated Mon Jul 06 15:40:52 GMT+08:00 2020
     */
    private String eventLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_info.event_desc
     *
     * @mbggenerated Mon Jul 06 15:40:52 GMT+08:00 2020
     */
    private String eventDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_info.oldperson_id
     *
     * @mbggenerated Mon Jul 06 15:40:52 GMT+08:00 2020
     */
    private Integer oldpersonId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_info.id
     *
     * @return the value of event_info.id
     *
     * @mbggenerated Mon Jul 06 15:40:52 GMT+08:00 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_info.id
     *
     * @param id the value for event_info.id
     *
     * @mbggenerated Mon Jul 06 15:40:52 GMT+08:00 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_info.event_type
     *
     * @return the value of event_info.event_type
     *
     * @mbggenerated Mon Jul 06 15:40:52 GMT+08:00 2020
     */
    public Integer getEventType() {
        return eventType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_info.event_type
     *
     * @param eventType the value for event_info.event_type
     *
     * @mbggenerated Mon Jul 06 15:40:52 GMT+08:00 2020
     */
    public void setEventType(Integer eventType) {
        this.eventType = eventType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_info.event_date
     *
     * @return the value of event_info.event_date
     *
     * @mbggenerated Mon Jul 06 15:40:52 GMT+08:00 2020
     */
    public Date getEventDate() {
        return eventDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_info.event_date
     *
     * @param eventDate the value for event_info.event_date
     *
     * @mbggenerated Mon Jul 06 15:40:52 GMT+08:00 2020
     */
    public void setEventDate(Date eventDate) {
        this.eventDate = eventDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_info.event_location
     *
     * @return the value of event_info.event_location
     *
     * @mbggenerated Mon Jul 06 15:40:52 GMT+08:00 2020
     */
    public String getEventLocation() {
        return eventLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_info.event_location
     *
     * @param eventLocation the value for event_info.event_location
     *
     * @mbggenerated Mon Jul 06 15:40:52 GMT+08:00 2020
     */
    public void setEventLocation(String eventLocation) {
        this.eventLocation = eventLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_info.event_desc
     *
     * @return the value of event_info.event_desc
     *
     * @mbggenerated Mon Jul 06 15:40:52 GMT+08:00 2020
     */
    public String getEventDesc() {
        return eventDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_info.event_desc
     *
     * @param eventDesc the value for event_info.event_desc
     *
     * @mbggenerated Mon Jul 06 15:40:52 GMT+08:00 2020
     */
    public void setEventDesc(String eventDesc) {
        this.eventDesc = eventDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_info.oldperson_id
     *
     * @return the value of event_info.oldperson_id
     *
     * @mbggenerated Mon Jul 06 15:40:52 GMT+08:00 2020
     */
    public Integer getOldpersonId() {
        return oldpersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_info.oldperson_id
     *
     * @param oldpersonId the value for event_info.oldperson_id
     *
     * @mbggenerated Mon Jul 06 15:40:52 GMT+08:00 2020
     */
    public void setOldpersonId(Integer oldpersonId) {
        this.oldpersonId = oldpersonId;
    }
}