package com.system.po;

import java.util.Date;

public class oldperson {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oldperson_info.ID
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oldperson_info.ORG_ID
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    private Integer orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oldperson_info.CLIENT_ID
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    private Integer clientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oldperson_info.username
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oldperson_info.gender
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oldperson_info.phone
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oldperson_info.id_card
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oldperson_info.birthday
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oldperson_info.checkin_date
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    private Date checkinDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oldperson_info.checkout_date
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    private Date checkoutDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oldperson_info.imgset_dir
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    private String imgsetDir;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oldperson_info.profile_photo
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    private String profilePhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oldperson_info.room_number
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    private String roomNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oldperson_info.firstguardian_name
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    private String firstguardianName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oldperson_info.firstguardian_relationship
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    private String firstguardianRelationship;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oldperson_info.firstguardian_phone
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    private String firstguardianPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oldperson_info.firstguardian_wechat
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    private String firstguardianWechat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oldperson_info.secondguardian_name
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    private String secondguardianName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oldperson_info.secondguardian_relationship
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    private String secondguardianRelationship;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oldperson_info.secondguardian_phone
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    private String secondguardianPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oldperson_info.secondguardian_wechat
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    private String secondguardianWechat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oldperson_info.health_state
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    private String healthState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oldperson_info.DESCRIPTION
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oldperson_info.ISACTIVE
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    private String isactive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oldperson_info.CREATED
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oldperson_info.CREATEBY
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    private Integer createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oldperson_info.UPDATED
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    private Date updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oldperson_info.UPDATEBY
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    private Integer updateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oldperson_info.REMOVE
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    private String remove;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldperson_info.ID
     *
     * @return the value of oldperson_info.ID
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldperson_info.ID
     *
     * @param id the value for oldperson_info.ID
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldperson_info.ORG_ID
     *
     * @return the value of oldperson_info.ORG_ID
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldperson_info.ORG_ID
     *
     * @param orgId the value for oldperson_info.ORG_ID
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldperson_info.CLIENT_ID
     *
     * @return the value of oldperson_info.CLIENT_ID
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public Integer getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldperson_info.CLIENT_ID
     *
     * @param clientId the value for oldperson_info.CLIENT_ID
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldperson_info.username
     *
     * @return the value of oldperson_info.username
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldperson_info.username
     *
     * @param username the value for oldperson_info.username
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldperson_info.gender
     *
     * @return the value of oldperson_info.gender
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldperson_info.gender
     *
     * @param gender the value for oldperson_info.gender
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldperson_info.phone
     *
     * @return the value of oldperson_info.phone
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldperson_info.phone
     *
     * @param phone the value for oldperson_info.phone
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldperson_info.id_card
     *
     * @return the value of oldperson_info.id_card
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldperson_info.id_card
     *
     * @param idCard the value for oldperson_info.id_card
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldperson_info.birthday
     *
     * @return the value of oldperson_info.birthday
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldperson_info.birthday
     *
     * @param birthday the value for oldperson_info.birthday
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldperson_info.checkin_date
     *
     * @return the value of oldperson_info.checkin_date
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public Date getCheckinDate() {
        return checkinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldperson_info.checkin_date
     *
     * @param checkinDate the value for oldperson_info.checkin_date
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public void setCheckinDate(Date checkinDate) {
        this.checkinDate = checkinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldperson_info.checkout_date
     *
     * @return the value of oldperson_info.checkout_date
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public Date getCheckoutDate() {
        return checkoutDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldperson_info.checkout_date
     *
     * @param checkoutDate the value for oldperson_info.checkout_date
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public void setCheckoutDate(Date checkoutDate) {
        this.checkoutDate = checkoutDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldperson_info.imgset_dir
     *
     * @return the value of oldperson_info.imgset_dir
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public String getImgsetDir() {
        return imgsetDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldperson_info.imgset_dir
     *
     * @param imgsetDir the value for oldperson_info.imgset_dir
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public void setImgsetDir(String imgsetDir) {
        this.imgsetDir = imgsetDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldperson_info.profile_photo
     *
     * @return the value of oldperson_info.profile_photo
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public String getProfilePhoto() {
        return profilePhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldperson_info.profile_photo
     *
     * @param profilePhoto the value for oldperson_info.profile_photo
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public void setProfilePhoto(String profilePhoto) {
        this.profilePhoto = profilePhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldperson_info.room_number
     *
     * @return the value of oldperson_info.room_number
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public String getRoomNumber() {
        return roomNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldperson_info.room_number
     *
     * @param roomNumber the value for oldperson_info.room_number
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public void setRoomNumber(String roomNumber) {
        this.roomNumber = roomNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldperson_info.firstguardian_name
     *
     * @return the value of oldperson_info.firstguardian_name
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public String getFirstguardianName() {
        return firstguardianName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldperson_info.firstguardian_name
     *
     * @param firstguardianName the value for oldperson_info.firstguardian_name
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public void setFirstguardianName(String firstguardianName) {
        this.firstguardianName = firstguardianName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldperson_info.firstguardian_relationship
     *
     * @return the value of oldperson_info.firstguardian_relationship
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public String getFirstguardianRelationship() {
        return firstguardianRelationship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldperson_info.firstguardian_relationship
     *
     * @param firstguardianRelationship the value for oldperson_info.firstguardian_relationship
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public void setFirstguardianRelationship(String firstguardianRelationship) {
        this.firstguardianRelationship = firstguardianRelationship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldperson_info.firstguardian_phone
     *
     * @return the value of oldperson_info.firstguardian_phone
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public String getFirstguardianPhone() {
        return firstguardianPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldperson_info.firstguardian_phone
     *
     * @param firstguardianPhone the value for oldperson_info.firstguardian_phone
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public void setFirstguardianPhone(String firstguardianPhone) {
        this.firstguardianPhone = firstguardianPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldperson_info.firstguardian_wechat
     *
     * @return the value of oldperson_info.firstguardian_wechat
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public String getFirstguardianWechat() {
        return firstguardianWechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldperson_info.firstguardian_wechat
     *
     * @param firstguardianWechat the value for oldperson_info.firstguardian_wechat
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public void setFirstguardianWechat(String firstguardianWechat) {
        this.firstguardianWechat = firstguardianWechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldperson_info.secondguardian_name
     *
     * @return the value of oldperson_info.secondguardian_name
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public String getSecondguardianName() {
        return secondguardianName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldperson_info.secondguardian_name
     *
     * @param secondguardianName the value for oldperson_info.secondguardian_name
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public void setSecondguardianName(String secondguardianName) {
        this.secondguardianName = secondguardianName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldperson_info.secondguardian_relationship
     *
     * @return the value of oldperson_info.secondguardian_relationship
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public String getSecondguardianRelationship() {
        return secondguardianRelationship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldperson_info.secondguardian_relationship
     *
     * @param secondguardianRelationship the value for oldperson_info.secondguardian_relationship
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public void setSecondguardianRelationship(String secondguardianRelationship) {
        this.secondguardianRelationship = secondguardianRelationship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldperson_info.secondguardian_phone
     *
     * @return the value of oldperson_info.secondguardian_phone
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public String getSecondguardianPhone() {
        return secondguardianPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldperson_info.secondguardian_phone
     *
     * @param secondguardianPhone the value for oldperson_info.secondguardian_phone
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public void setSecondguardianPhone(String secondguardianPhone) {
        this.secondguardianPhone = secondguardianPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldperson_info.secondguardian_wechat
     *
     * @return the value of oldperson_info.secondguardian_wechat
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public String getSecondguardianWechat() {
        return secondguardianWechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldperson_info.secondguardian_wechat
     *
     * @param secondguardianWechat the value for oldperson_info.secondguardian_wechat
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public void setSecondguardianWechat(String secondguardianWechat) {
        this.secondguardianWechat = secondguardianWechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldperson_info.health_state
     *
     * @return the value of oldperson_info.health_state
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public String getHealthState() {
        return healthState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldperson_info.health_state
     *
     * @param healthState the value for oldperson_info.health_state
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public void setHealthState(String healthState) {
        this.healthState = healthState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldperson_info.DESCRIPTION
     *
     * @return the value of oldperson_info.DESCRIPTION
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldperson_info.DESCRIPTION
     *
     * @param description the value for oldperson_info.DESCRIPTION
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldperson_info.ISACTIVE
     *
     * @return the value of oldperson_info.ISACTIVE
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public String getIsactive() {
        return isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldperson_info.ISACTIVE
     *
     * @param isactive the value for oldperson_info.ISACTIVE
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public void setIsactive(String isactive) {
        this.isactive = isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldperson_info.CREATED
     *
     * @return the value of oldperson_info.CREATED
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldperson_info.CREATED
     *
     * @param created the value for oldperson_info.CREATED
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldperson_info.CREATEBY
     *
     * @return the value of oldperson_info.CREATEBY
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public Integer getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldperson_info.CREATEBY
     *
     * @param createby the value for oldperson_info.CREATEBY
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public void setCreateby(Integer createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldperson_info.UPDATED
     *
     * @return the value of oldperson_info.UPDATED
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldperson_info.UPDATED
     *
     * @param updated the value for oldperson_info.UPDATED
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldperson_info.UPDATEBY
     *
     * @return the value of oldperson_info.UPDATEBY
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public Integer getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldperson_info.UPDATEBY
     *
     * @param updateby the value for oldperson_info.UPDATEBY
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public void setUpdateby(Integer updateby) {
        this.updateby = updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldperson_info.REMOVE
     *
     * @return the value of oldperson_info.REMOVE
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public String getRemove() {
        return remove;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldperson_info.REMOVE
     *
     * @param remove the value for oldperson_info.REMOVE
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public void setRemove(String remove) {
        this.remove = remove;
    }
}