package com.system.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class oldpersonExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oldperson_info
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oldperson_info
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oldperson_info
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oldperson_info
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public oldpersonExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oldperson_info
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oldperson_info
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oldperson_info
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oldperson_info
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oldperson_info
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oldperson_info
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oldperson_info
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oldperson_info
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oldperson_info
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oldperson_info
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oldperson_info
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrgIdIsNull() {
            addCriterion("ORG_ID is null");
            return (Criteria) this;
        }

        public Criteria andOrgIdIsNotNull() {
            addCriterion("ORG_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOrgIdEqualTo(Integer value) {
            addCriterion("ORG_ID =", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotEqualTo(Integer value) {
            addCriterion("ORG_ID <>", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdGreaterThan(Integer value) {
            addCriterion("ORG_ID >", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ORG_ID >=", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdLessThan(Integer value) {
            addCriterion("ORG_ID <", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdLessThanOrEqualTo(Integer value) {
            addCriterion("ORG_ID <=", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdIn(List<Integer> values) {
            addCriterion("ORG_ID in", values, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotIn(List<Integer> values) {
            addCriterion("ORG_ID not in", values, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdBetween(Integer value1, Integer value2) {
            addCriterion("ORG_ID between", value1, value2, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ORG_ID not between", value1, value2, "orgId");
            return (Criteria) this;
        }

        public Criteria andClientIdIsNull() {
            addCriterion("CLIENT_ID is null");
            return (Criteria) this;
        }

        public Criteria andClientIdIsNotNull() {
            addCriterion("CLIENT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andClientIdEqualTo(Integer value) {
            addCriterion("CLIENT_ID =", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdNotEqualTo(Integer value) {
            addCriterion("CLIENT_ID <>", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdGreaterThan(Integer value) {
            addCriterion("CLIENT_ID >", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("CLIENT_ID >=", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdLessThan(Integer value) {
            addCriterion("CLIENT_ID <", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdLessThanOrEqualTo(Integer value) {
            addCriterion("CLIENT_ID <=", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdIn(List<Integer> values) {
            addCriterion("CLIENT_ID in", values, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdNotIn(List<Integer> values) {
            addCriterion("CLIENT_ID not in", values, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdBetween(Integer value1, Integer value2) {
            addCriterion("CLIENT_ID between", value1, value2, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdNotBetween(Integer value1, Integer value2) {
            addCriterion("CLIENT_ID not between", value1, value2, "clientId");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("username is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("username is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("username =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("username <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("username >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("username >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("username <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("username <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("username like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("username not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("username in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("username not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("username between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("username not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andGenderIsNull() {
            addCriterion("gender is null");
            return (Criteria) this;
        }

        public Criteria andGenderIsNotNull() {
            addCriterion("gender is not null");
            return (Criteria) this;
        }

        public Criteria andGenderEqualTo(String value) {
            addCriterion("gender =", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotEqualTo(String value) {
            addCriterion("gender <>", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThan(String value) {
            addCriterion("gender >", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThanOrEqualTo(String value) {
            addCriterion("gender >=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThan(String value) {
            addCriterion("gender <", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThanOrEqualTo(String value) {
            addCriterion("gender <=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLike(String value) {
            addCriterion("gender like", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotLike(String value) {
            addCriterion("gender not like", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderIn(List<String> values) {
            addCriterion("gender in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotIn(List<String> values) {
            addCriterion("gender not in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderBetween(String value1, String value2) {
            addCriterion("gender between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotBetween(String value1, String value2) {
            addCriterion("gender not between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("phone is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("phone is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("phone =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("phone <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("phone >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("phone >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("phone <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("phone <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("phone like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("phone not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("phone in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("phone not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("phone between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("phone not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andIdCardIsNull() {
            addCriterion("id_card is null");
            return (Criteria) this;
        }

        public Criteria andIdCardIsNotNull() {
            addCriterion("id_card is not null");
            return (Criteria) this;
        }

        public Criteria andIdCardEqualTo(String value) {
            addCriterion("id_card =", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotEqualTo(String value) {
            addCriterion("id_card <>", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardGreaterThan(String value) {
            addCriterion("id_card >", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardGreaterThanOrEqualTo(String value) {
            addCriterion("id_card >=", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardLessThan(String value) {
            addCriterion("id_card <", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardLessThanOrEqualTo(String value) {
            addCriterion("id_card <=", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardLike(String value) {
            addCriterion("id_card like", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotLike(String value) {
            addCriterion("id_card not like", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardIn(List<String> values) {
            addCriterion("id_card in", values, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotIn(List<String> values) {
            addCriterion("id_card not in", values, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardBetween(String value1, String value2) {
            addCriterion("id_card between", value1, value2, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotBetween(String value1, String value2) {
            addCriterion("id_card not between", value1, value2, "idCard");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNull() {
            addCriterion("birthday is null");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNotNull() {
            addCriterion("birthday is not null");
            return (Criteria) this;
        }

        public Criteria andBirthdayEqualTo(Date value) {
            addCriterion("birthday =", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotEqualTo(Date value) {
            addCriterion("birthday <>", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThan(Date value) {
            addCriterion("birthday >", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThanOrEqualTo(Date value) {
            addCriterion("birthday >=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThan(Date value) {
            addCriterion("birthday <", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThanOrEqualTo(Date value) {
            addCriterion("birthday <=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayIn(List<Date> values) {
            addCriterion("birthday in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotIn(List<Date> values) {
            addCriterion("birthday not in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayBetween(Date value1, Date value2) {
            addCriterion("birthday between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotBetween(Date value1, Date value2) {
            addCriterion("birthday not between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andCheckinDateIsNull() {
            addCriterion("checkin_date is null");
            return (Criteria) this;
        }

        public Criteria andCheckinDateIsNotNull() {
            addCriterion("checkin_date is not null");
            return (Criteria) this;
        }

        public Criteria andCheckinDateEqualTo(Date value) {
            addCriterion("checkin_date =", value, "checkinDate");
            return (Criteria) this;
        }

        public Criteria andCheckinDateNotEqualTo(Date value) {
            addCriterion("checkin_date <>", value, "checkinDate");
            return (Criteria) this;
        }

        public Criteria andCheckinDateGreaterThan(Date value) {
            addCriterion("checkin_date >", value, "checkinDate");
            return (Criteria) this;
        }

        public Criteria andCheckinDateGreaterThanOrEqualTo(Date value) {
            addCriterion("checkin_date >=", value, "checkinDate");
            return (Criteria) this;
        }

        public Criteria andCheckinDateLessThan(Date value) {
            addCriterion("checkin_date <", value, "checkinDate");
            return (Criteria) this;
        }

        public Criteria andCheckinDateLessThanOrEqualTo(Date value) {
            addCriterion("checkin_date <=", value, "checkinDate");
            return (Criteria) this;
        }

        public Criteria andCheckinDateIn(List<Date> values) {
            addCriterion("checkin_date in", values, "checkinDate");
            return (Criteria) this;
        }

        public Criteria andCheckinDateNotIn(List<Date> values) {
            addCriterion("checkin_date not in", values, "checkinDate");
            return (Criteria) this;
        }

        public Criteria andCheckinDateBetween(Date value1, Date value2) {
            addCriterion("checkin_date between", value1, value2, "checkinDate");
            return (Criteria) this;
        }

        public Criteria andCheckinDateNotBetween(Date value1, Date value2) {
            addCriterion("checkin_date not between", value1, value2, "checkinDate");
            return (Criteria) this;
        }

        public Criteria andCheckoutDateIsNull() {
            addCriterion("checkout_date is null");
            return (Criteria) this;
        }

        public Criteria andCheckoutDateIsNotNull() {
            addCriterion("checkout_date is not null");
            return (Criteria) this;
        }

        public Criteria andCheckoutDateEqualTo(Date value) {
            addCriterion("checkout_date =", value, "checkoutDate");
            return (Criteria) this;
        }

        public Criteria andCheckoutDateNotEqualTo(Date value) {
            addCriterion("checkout_date <>", value, "checkoutDate");
            return (Criteria) this;
        }

        public Criteria andCheckoutDateGreaterThan(Date value) {
            addCriterion("checkout_date >", value, "checkoutDate");
            return (Criteria) this;
        }

        public Criteria andCheckoutDateGreaterThanOrEqualTo(Date value) {
            addCriterion("checkout_date >=", value, "checkoutDate");
            return (Criteria) this;
        }

        public Criteria andCheckoutDateLessThan(Date value) {
            addCriterion("checkout_date <", value, "checkoutDate");
            return (Criteria) this;
        }

        public Criteria andCheckoutDateLessThanOrEqualTo(Date value) {
            addCriterion("checkout_date <=", value, "checkoutDate");
            return (Criteria) this;
        }

        public Criteria andCheckoutDateIn(List<Date> values) {
            addCriterion("checkout_date in", values, "checkoutDate");
            return (Criteria) this;
        }

        public Criteria andCheckoutDateNotIn(List<Date> values) {
            addCriterion("checkout_date not in", values, "checkoutDate");
            return (Criteria) this;
        }

        public Criteria andCheckoutDateBetween(Date value1, Date value2) {
            addCriterion("checkout_date between", value1, value2, "checkoutDate");
            return (Criteria) this;
        }

        public Criteria andCheckoutDateNotBetween(Date value1, Date value2) {
            addCriterion("checkout_date not between", value1, value2, "checkoutDate");
            return (Criteria) this;
        }

        public Criteria andImgsetDirIsNull() {
            addCriterion("imgset_dir is null");
            return (Criteria) this;
        }

        public Criteria andImgsetDirIsNotNull() {
            addCriterion("imgset_dir is not null");
            return (Criteria) this;
        }

        public Criteria andImgsetDirEqualTo(String value) {
            addCriterion("imgset_dir =", value, "imgsetDir");
            return (Criteria) this;
        }

        public Criteria andImgsetDirNotEqualTo(String value) {
            addCriterion("imgset_dir <>", value, "imgsetDir");
            return (Criteria) this;
        }

        public Criteria andImgsetDirGreaterThan(String value) {
            addCriterion("imgset_dir >", value, "imgsetDir");
            return (Criteria) this;
        }

        public Criteria andImgsetDirGreaterThanOrEqualTo(String value) {
            addCriterion("imgset_dir >=", value, "imgsetDir");
            return (Criteria) this;
        }

        public Criteria andImgsetDirLessThan(String value) {
            addCriterion("imgset_dir <", value, "imgsetDir");
            return (Criteria) this;
        }

        public Criteria andImgsetDirLessThanOrEqualTo(String value) {
            addCriterion("imgset_dir <=", value, "imgsetDir");
            return (Criteria) this;
        }

        public Criteria andImgsetDirLike(String value) {
            addCriterion("imgset_dir like", value, "imgsetDir");
            return (Criteria) this;
        }

        public Criteria andImgsetDirNotLike(String value) {
            addCriterion("imgset_dir not like", value, "imgsetDir");
            return (Criteria) this;
        }

        public Criteria andImgsetDirIn(List<String> values) {
            addCriterion("imgset_dir in", values, "imgsetDir");
            return (Criteria) this;
        }

        public Criteria andImgsetDirNotIn(List<String> values) {
            addCriterion("imgset_dir not in", values, "imgsetDir");
            return (Criteria) this;
        }

        public Criteria andImgsetDirBetween(String value1, String value2) {
            addCriterion("imgset_dir between", value1, value2, "imgsetDir");
            return (Criteria) this;
        }

        public Criteria andImgsetDirNotBetween(String value1, String value2) {
            addCriterion("imgset_dir not between", value1, value2, "imgsetDir");
            return (Criteria) this;
        }

        public Criteria andProfilePhotoIsNull() {
            addCriterion("profile_photo is null");
            return (Criteria) this;
        }

        public Criteria andProfilePhotoIsNotNull() {
            addCriterion("profile_photo is not null");
            return (Criteria) this;
        }

        public Criteria andProfilePhotoEqualTo(String value) {
            addCriterion("profile_photo =", value, "profilePhoto");
            return (Criteria) this;
        }

        public Criteria andProfilePhotoNotEqualTo(String value) {
            addCriterion("profile_photo <>", value, "profilePhoto");
            return (Criteria) this;
        }

        public Criteria andProfilePhotoGreaterThan(String value) {
            addCriterion("profile_photo >", value, "profilePhoto");
            return (Criteria) this;
        }

        public Criteria andProfilePhotoGreaterThanOrEqualTo(String value) {
            addCriterion("profile_photo >=", value, "profilePhoto");
            return (Criteria) this;
        }

        public Criteria andProfilePhotoLessThan(String value) {
            addCriterion("profile_photo <", value, "profilePhoto");
            return (Criteria) this;
        }

        public Criteria andProfilePhotoLessThanOrEqualTo(String value) {
            addCriterion("profile_photo <=", value, "profilePhoto");
            return (Criteria) this;
        }

        public Criteria andProfilePhotoLike(String value) {
            addCriterion("profile_photo like", value, "profilePhoto");
            return (Criteria) this;
        }

        public Criteria andProfilePhotoNotLike(String value) {
            addCriterion("profile_photo not like", value, "profilePhoto");
            return (Criteria) this;
        }

        public Criteria andProfilePhotoIn(List<String> values) {
            addCriterion("profile_photo in", values, "profilePhoto");
            return (Criteria) this;
        }

        public Criteria andProfilePhotoNotIn(List<String> values) {
            addCriterion("profile_photo not in", values, "profilePhoto");
            return (Criteria) this;
        }

        public Criteria andProfilePhotoBetween(String value1, String value2) {
            addCriterion("profile_photo between", value1, value2, "profilePhoto");
            return (Criteria) this;
        }

        public Criteria andProfilePhotoNotBetween(String value1, String value2) {
            addCriterion("profile_photo not between", value1, value2, "profilePhoto");
            return (Criteria) this;
        }

        public Criteria andRoomNumberIsNull() {
            addCriterion("room_number is null");
            return (Criteria) this;
        }

        public Criteria andRoomNumberIsNotNull() {
            addCriterion("room_number is not null");
            return (Criteria) this;
        }

        public Criteria andRoomNumberEqualTo(String value) {
            addCriterion("room_number =", value, "roomNumber");
            return (Criteria) this;
        }

        public Criteria andRoomNumberNotEqualTo(String value) {
            addCriterion("room_number <>", value, "roomNumber");
            return (Criteria) this;
        }

        public Criteria andRoomNumberGreaterThan(String value) {
            addCriterion("room_number >", value, "roomNumber");
            return (Criteria) this;
        }

        public Criteria andRoomNumberGreaterThanOrEqualTo(String value) {
            addCriterion("room_number >=", value, "roomNumber");
            return (Criteria) this;
        }

        public Criteria andRoomNumberLessThan(String value) {
            addCriterion("room_number <", value, "roomNumber");
            return (Criteria) this;
        }

        public Criteria andRoomNumberLessThanOrEqualTo(String value) {
            addCriterion("room_number <=", value, "roomNumber");
            return (Criteria) this;
        }

        public Criteria andRoomNumberLike(String value) {
            addCriterion("room_number like", value, "roomNumber");
            return (Criteria) this;
        }

        public Criteria andRoomNumberNotLike(String value) {
            addCriterion("room_number not like", value, "roomNumber");
            return (Criteria) this;
        }

        public Criteria andRoomNumberIn(List<String> values) {
            addCriterion("room_number in", values, "roomNumber");
            return (Criteria) this;
        }

        public Criteria andRoomNumberNotIn(List<String> values) {
            addCriterion("room_number not in", values, "roomNumber");
            return (Criteria) this;
        }

        public Criteria andRoomNumberBetween(String value1, String value2) {
            addCriterion("room_number between", value1, value2, "roomNumber");
            return (Criteria) this;
        }

        public Criteria andRoomNumberNotBetween(String value1, String value2) {
            addCriterion("room_number not between", value1, value2, "roomNumber");
            return (Criteria) this;
        }

        public Criteria andFirstguardianNameIsNull() {
            addCriterion("firstguardian_name is null");
            return (Criteria) this;
        }

        public Criteria andFirstguardianNameIsNotNull() {
            addCriterion("firstguardian_name is not null");
            return (Criteria) this;
        }

        public Criteria andFirstguardianNameEqualTo(String value) {
            addCriterion("firstguardian_name =", value, "firstguardianName");
            return (Criteria) this;
        }

        public Criteria andFirstguardianNameNotEqualTo(String value) {
            addCriterion("firstguardian_name <>", value, "firstguardianName");
            return (Criteria) this;
        }

        public Criteria andFirstguardianNameGreaterThan(String value) {
            addCriterion("firstguardian_name >", value, "firstguardianName");
            return (Criteria) this;
        }

        public Criteria andFirstguardianNameGreaterThanOrEqualTo(String value) {
            addCriterion("firstguardian_name >=", value, "firstguardianName");
            return (Criteria) this;
        }

        public Criteria andFirstguardianNameLessThan(String value) {
            addCriterion("firstguardian_name <", value, "firstguardianName");
            return (Criteria) this;
        }

        public Criteria andFirstguardianNameLessThanOrEqualTo(String value) {
            addCriterion("firstguardian_name <=", value, "firstguardianName");
            return (Criteria) this;
        }

        public Criteria andFirstguardianNameLike(String value) {
            addCriterion("firstguardian_name like", value, "firstguardianName");
            return (Criteria) this;
        }

        public Criteria andFirstguardianNameNotLike(String value) {
            addCriterion("firstguardian_name not like", value, "firstguardianName");
            return (Criteria) this;
        }

        public Criteria andFirstguardianNameIn(List<String> values) {
            addCriterion("firstguardian_name in", values, "firstguardianName");
            return (Criteria) this;
        }

        public Criteria andFirstguardianNameNotIn(List<String> values) {
            addCriterion("firstguardian_name not in", values, "firstguardianName");
            return (Criteria) this;
        }

        public Criteria andFirstguardianNameBetween(String value1, String value2) {
            addCriterion("firstguardian_name between", value1, value2, "firstguardianName");
            return (Criteria) this;
        }

        public Criteria andFirstguardianNameNotBetween(String value1, String value2) {
            addCriterion("firstguardian_name not between", value1, value2, "firstguardianName");
            return (Criteria) this;
        }

        public Criteria andFirstguardianRelationshipIsNull() {
            addCriterion("firstguardian_relationship is null");
            return (Criteria) this;
        }

        public Criteria andFirstguardianRelationshipIsNotNull() {
            addCriterion("firstguardian_relationship is not null");
            return (Criteria) this;
        }

        public Criteria andFirstguardianRelationshipEqualTo(String value) {
            addCriterion("firstguardian_relationship =", value, "firstguardianRelationship");
            return (Criteria) this;
        }

        public Criteria andFirstguardianRelationshipNotEqualTo(String value) {
            addCriterion("firstguardian_relationship <>", value, "firstguardianRelationship");
            return (Criteria) this;
        }

        public Criteria andFirstguardianRelationshipGreaterThan(String value) {
            addCriterion("firstguardian_relationship >", value, "firstguardianRelationship");
            return (Criteria) this;
        }

        public Criteria andFirstguardianRelationshipGreaterThanOrEqualTo(String value) {
            addCriterion("firstguardian_relationship >=", value, "firstguardianRelationship");
            return (Criteria) this;
        }

        public Criteria andFirstguardianRelationshipLessThan(String value) {
            addCriterion("firstguardian_relationship <", value, "firstguardianRelationship");
            return (Criteria) this;
        }

        public Criteria andFirstguardianRelationshipLessThanOrEqualTo(String value) {
            addCriterion("firstguardian_relationship <=", value, "firstguardianRelationship");
            return (Criteria) this;
        }

        public Criteria andFirstguardianRelationshipLike(String value) {
            addCriterion("firstguardian_relationship like", value, "firstguardianRelationship");
            return (Criteria) this;
        }

        public Criteria andFirstguardianRelationshipNotLike(String value) {
            addCriterion("firstguardian_relationship not like", value, "firstguardianRelationship");
            return (Criteria) this;
        }

        public Criteria andFirstguardianRelationshipIn(List<String> values) {
            addCriterion("firstguardian_relationship in", values, "firstguardianRelationship");
            return (Criteria) this;
        }

        public Criteria andFirstguardianRelationshipNotIn(List<String> values) {
            addCriterion("firstguardian_relationship not in", values, "firstguardianRelationship");
            return (Criteria) this;
        }

        public Criteria andFirstguardianRelationshipBetween(String value1, String value2) {
            addCriterion("firstguardian_relationship between", value1, value2, "firstguardianRelationship");
            return (Criteria) this;
        }

        public Criteria andFirstguardianRelationshipNotBetween(String value1, String value2) {
            addCriterion("firstguardian_relationship not between", value1, value2, "firstguardianRelationship");
            return (Criteria) this;
        }

        public Criteria andFirstguardianPhoneIsNull() {
            addCriterion("firstguardian_phone is null");
            return (Criteria) this;
        }

        public Criteria andFirstguardianPhoneIsNotNull() {
            addCriterion("firstguardian_phone is not null");
            return (Criteria) this;
        }

        public Criteria andFirstguardianPhoneEqualTo(String value) {
            addCriterion("firstguardian_phone =", value, "firstguardianPhone");
            return (Criteria) this;
        }

        public Criteria andFirstguardianPhoneNotEqualTo(String value) {
            addCriterion("firstguardian_phone <>", value, "firstguardianPhone");
            return (Criteria) this;
        }

        public Criteria andFirstguardianPhoneGreaterThan(String value) {
            addCriterion("firstguardian_phone >", value, "firstguardianPhone");
            return (Criteria) this;
        }

        public Criteria andFirstguardianPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("firstguardian_phone >=", value, "firstguardianPhone");
            return (Criteria) this;
        }

        public Criteria andFirstguardianPhoneLessThan(String value) {
            addCriterion("firstguardian_phone <", value, "firstguardianPhone");
            return (Criteria) this;
        }

        public Criteria andFirstguardianPhoneLessThanOrEqualTo(String value) {
            addCriterion("firstguardian_phone <=", value, "firstguardianPhone");
            return (Criteria) this;
        }

        public Criteria andFirstguardianPhoneLike(String value) {
            addCriterion("firstguardian_phone like", value, "firstguardianPhone");
            return (Criteria) this;
        }

        public Criteria andFirstguardianPhoneNotLike(String value) {
            addCriterion("firstguardian_phone not like", value, "firstguardianPhone");
            return (Criteria) this;
        }

        public Criteria andFirstguardianPhoneIn(List<String> values) {
            addCriterion("firstguardian_phone in", values, "firstguardianPhone");
            return (Criteria) this;
        }

        public Criteria andFirstguardianPhoneNotIn(List<String> values) {
            addCriterion("firstguardian_phone not in", values, "firstguardianPhone");
            return (Criteria) this;
        }

        public Criteria andFirstguardianPhoneBetween(String value1, String value2) {
            addCriterion("firstguardian_phone between", value1, value2, "firstguardianPhone");
            return (Criteria) this;
        }

        public Criteria andFirstguardianPhoneNotBetween(String value1, String value2) {
            addCriterion("firstguardian_phone not between", value1, value2, "firstguardianPhone");
            return (Criteria) this;
        }

        public Criteria andFirstguardianWechatIsNull() {
            addCriterion("firstguardian_wechat is null");
            return (Criteria) this;
        }

        public Criteria andFirstguardianWechatIsNotNull() {
            addCriterion("firstguardian_wechat is not null");
            return (Criteria) this;
        }

        public Criteria andFirstguardianWechatEqualTo(String value) {
            addCriterion("firstguardian_wechat =", value, "firstguardianWechat");
            return (Criteria) this;
        }

        public Criteria andFirstguardianWechatNotEqualTo(String value) {
            addCriterion("firstguardian_wechat <>", value, "firstguardianWechat");
            return (Criteria) this;
        }

        public Criteria andFirstguardianWechatGreaterThan(String value) {
            addCriterion("firstguardian_wechat >", value, "firstguardianWechat");
            return (Criteria) this;
        }

        public Criteria andFirstguardianWechatGreaterThanOrEqualTo(String value) {
            addCriterion("firstguardian_wechat >=", value, "firstguardianWechat");
            return (Criteria) this;
        }

        public Criteria andFirstguardianWechatLessThan(String value) {
            addCriterion("firstguardian_wechat <", value, "firstguardianWechat");
            return (Criteria) this;
        }

        public Criteria andFirstguardianWechatLessThanOrEqualTo(String value) {
            addCriterion("firstguardian_wechat <=", value, "firstguardianWechat");
            return (Criteria) this;
        }

        public Criteria andFirstguardianWechatLike(String value) {
            addCriterion("firstguardian_wechat like", value, "firstguardianWechat");
            return (Criteria) this;
        }

        public Criteria andFirstguardianWechatNotLike(String value) {
            addCriterion("firstguardian_wechat not like", value, "firstguardianWechat");
            return (Criteria) this;
        }

        public Criteria andFirstguardianWechatIn(List<String> values) {
            addCriterion("firstguardian_wechat in", values, "firstguardianWechat");
            return (Criteria) this;
        }

        public Criteria andFirstguardianWechatNotIn(List<String> values) {
            addCriterion("firstguardian_wechat not in", values, "firstguardianWechat");
            return (Criteria) this;
        }

        public Criteria andFirstguardianWechatBetween(String value1, String value2) {
            addCriterion("firstguardian_wechat between", value1, value2, "firstguardianWechat");
            return (Criteria) this;
        }

        public Criteria andFirstguardianWechatNotBetween(String value1, String value2) {
            addCriterion("firstguardian_wechat not between", value1, value2, "firstguardianWechat");
            return (Criteria) this;
        }

        public Criteria andSecondguardianNameIsNull() {
            addCriterion("secondguardian_name is null");
            return (Criteria) this;
        }

        public Criteria andSecondguardianNameIsNotNull() {
            addCriterion("secondguardian_name is not null");
            return (Criteria) this;
        }

        public Criteria andSecondguardianNameEqualTo(String value) {
            addCriterion("secondguardian_name =", value, "secondguardianName");
            return (Criteria) this;
        }

        public Criteria andSecondguardianNameNotEqualTo(String value) {
            addCriterion("secondguardian_name <>", value, "secondguardianName");
            return (Criteria) this;
        }

        public Criteria andSecondguardianNameGreaterThan(String value) {
            addCriterion("secondguardian_name >", value, "secondguardianName");
            return (Criteria) this;
        }

        public Criteria andSecondguardianNameGreaterThanOrEqualTo(String value) {
            addCriterion("secondguardian_name >=", value, "secondguardianName");
            return (Criteria) this;
        }

        public Criteria andSecondguardianNameLessThan(String value) {
            addCriterion("secondguardian_name <", value, "secondguardianName");
            return (Criteria) this;
        }

        public Criteria andSecondguardianNameLessThanOrEqualTo(String value) {
            addCriterion("secondguardian_name <=", value, "secondguardianName");
            return (Criteria) this;
        }

        public Criteria andSecondguardianNameLike(String value) {
            addCriterion("secondguardian_name like", value, "secondguardianName");
            return (Criteria) this;
        }

        public Criteria andSecondguardianNameNotLike(String value) {
            addCriterion("secondguardian_name not like", value, "secondguardianName");
            return (Criteria) this;
        }

        public Criteria andSecondguardianNameIn(List<String> values) {
            addCriterion("secondguardian_name in", values, "secondguardianName");
            return (Criteria) this;
        }

        public Criteria andSecondguardianNameNotIn(List<String> values) {
            addCriterion("secondguardian_name not in", values, "secondguardianName");
            return (Criteria) this;
        }

        public Criteria andSecondguardianNameBetween(String value1, String value2) {
            addCriterion("secondguardian_name between", value1, value2, "secondguardianName");
            return (Criteria) this;
        }

        public Criteria andSecondguardianNameNotBetween(String value1, String value2) {
            addCriterion("secondguardian_name not between", value1, value2, "secondguardianName");
            return (Criteria) this;
        }

        public Criteria andSecondguardianRelationshipIsNull() {
            addCriterion("secondguardian_relationship is null");
            return (Criteria) this;
        }

        public Criteria andSecondguardianRelationshipIsNotNull() {
            addCriterion("secondguardian_relationship is not null");
            return (Criteria) this;
        }

        public Criteria andSecondguardianRelationshipEqualTo(String value) {
            addCriterion("secondguardian_relationship =", value, "secondguardianRelationship");
            return (Criteria) this;
        }

        public Criteria andSecondguardianRelationshipNotEqualTo(String value) {
            addCriterion("secondguardian_relationship <>", value, "secondguardianRelationship");
            return (Criteria) this;
        }

        public Criteria andSecondguardianRelationshipGreaterThan(String value) {
            addCriterion("secondguardian_relationship >", value, "secondguardianRelationship");
            return (Criteria) this;
        }

        public Criteria andSecondguardianRelationshipGreaterThanOrEqualTo(String value) {
            addCriterion("secondguardian_relationship >=", value, "secondguardianRelationship");
            return (Criteria) this;
        }

        public Criteria andSecondguardianRelationshipLessThan(String value) {
            addCriterion("secondguardian_relationship <", value, "secondguardianRelationship");
            return (Criteria) this;
        }

        public Criteria andSecondguardianRelationshipLessThanOrEqualTo(String value) {
            addCriterion("secondguardian_relationship <=", value, "secondguardianRelationship");
            return (Criteria) this;
        }

        public Criteria andSecondguardianRelationshipLike(String value) {
            addCriterion("secondguardian_relationship like", value, "secondguardianRelationship");
            return (Criteria) this;
        }

        public Criteria andSecondguardianRelationshipNotLike(String value) {
            addCriterion("secondguardian_relationship not like", value, "secondguardianRelationship");
            return (Criteria) this;
        }

        public Criteria andSecondguardianRelationshipIn(List<String> values) {
            addCriterion("secondguardian_relationship in", values, "secondguardianRelationship");
            return (Criteria) this;
        }

        public Criteria andSecondguardianRelationshipNotIn(List<String> values) {
            addCriterion("secondguardian_relationship not in", values, "secondguardianRelationship");
            return (Criteria) this;
        }

        public Criteria andSecondguardianRelationshipBetween(String value1, String value2) {
            addCriterion("secondguardian_relationship between", value1, value2, "secondguardianRelationship");
            return (Criteria) this;
        }

        public Criteria andSecondguardianRelationshipNotBetween(String value1, String value2) {
            addCriterion("secondguardian_relationship not between", value1, value2, "secondguardianRelationship");
            return (Criteria) this;
        }

        public Criteria andSecondguardianPhoneIsNull() {
            addCriterion("secondguardian_phone is null");
            return (Criteria) this;
        }

        public Criteria andSecondguardianPhoneIsNotNull() {
            addCriterion("secondguardian_phone is not null");
            return (Criteria) this;
        }

        public Criteria andSecondguardianPhoneEqualTo(String value) {
            addCriterion("secondguardian_phone =", value, "secondguardianPhone");
            return (Criteria) this;
        }

        public Criteria andSecondguardianPhoneNotEqualTo(String value) {
            addCriterion("secondguardian_phone <>", value, "secondguardianPhone");
            return (Criteria) this;
        }

        public Criteria andSecondguardianPhoneGreaterThan(String value) {
            addCriterion("secondguardian_phone >", value, "secondguardianPhone");
            return (Criteria) this;
        }

        public Criteria andSecondguardianPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("secondguardian_phone >=", value, "secondguardianPhone");
            return (Criteria) this;
        }

        public Criteria andSecondguardianPhoneLessThan(String value) {
            addCriterion("secondguardian_phone <", value, "secondguardianPhone");
            return (Criteria) this;
        }

        public Criteria andSecondguardianPhoneLessThanOrEqualTo(String value) {
            addCriterion("secondguardian_phone <=", value, "secondguardianPhone");
            return (Criteria) this;
        }

        public Criteria andSecondguardianPhoneLike(String value) {
            addCriterion("secondguardian_phone like", value, "secondguardianPhone");
            return (Criteria) this;
        }

        public Criteria andSecondguardianPhoneNotLike(String value) {
            addCriterion("secondguardian_phone not like", value, "secondguardianPhone");
            return (Criteria) this;
        }

        public Criteria andSecondguardianPhoneIn(List<String> values) {
            addCriterion("secondguardian_phone in", values, "secondguardianPhone");
            return (Criteria) this;
        }

        public Criteria andSecondguardianPhoneNotIn(List<String> values) {
            addCriterion("secondguardian_phone not in", values, "secondguardianPhone");
            return (Criteria) this;
        }

        public Criteria andSecondguardianPhoneBetween(String value1, String value2) {
            addCriterion("secondguardian_phone between", value1, value2, "secondguardianPhone");
            return (Criteria) this;
        }

        public Criteria andSecondguardianPhoneNotBetween(String value1, String value2) {
            addCriterion("secondguardian_phone not between", value1, value2, "secondguardianPhone");
            return (Criteria) this;
        }

        public Criteria andSecondguardianWechatIsNull() {
            addCriterion("secondguardian_wechat is null");
            return (Criteria) this;
        }

        public Criteria andSecondguardianWechatIsNotNull() {
            addCriterion("secondguardian_wechat is not null");
            return (Criteria) this;
        }

        public Criteria andSecondguardianWechatEqualTo(String value) {
            addCriterion("secondguardian_wechat =", value, "secondguardianWechat");
            return (Criteria) this;
        }

        public Criteria andSecondguardianWechatNotEqualTo(String value) {
            addCriterion("secondguardian_wechat <>", value, "secondguardianWechat");
            return (Criteria) this;
        }

        public Criteria andSecondguardianWechatGreaterThan(String value) {
            addCriterion("secondguardian_wechat >", value, "secondguardianWechat");
            return (Criteria) this;
        }

        public Criteria andSecondguardianWechatGreaterThanOrEqualTo(String value) {
            addCriterion("secondguardian_wechat >=", value, "secondguardianWechat");
            return (Criteria) this;
        }

        public Criteria andSecondguardianWechatLessThan(String value) {
            addCriterion("secondguardian_wechat <", value, "secondguardianWechat");
            return (Criteria) this;
        }

        public Criteria andSecondguardianWechatLessThanOrEqualTo(String value) {
            addCriterion("secondguardian_wechat <=", value, "secondguardianWechat");
            return (Criteria) this;
        }

        public Criteria andSecondguardianWechatLike(String value) {
            addCriterion("secondguardian_wechat like", value, "secondguardianWechat");
            return (Criteria) this;
        }

        public Criteria andSecondguardianWechatNotLike(String value) {
            addCriterion("secondguardian_wechat not like", value, "secondguardianWechat");
            return (Criteria) this;
        }

        public Criteria andSecondguardianWechatIn(List<String> values) {
            addCriterion("secondguardian_wechat in", values, "secondguardianWechat");
            return (Criteria) this;
        }

        public Criteria andSecondguardianWechatNotIn(List<String> values) {
            addCriterion("secondguardian_wechat not in", values, "secondguardianWechat");
            return (Criteria) this;
        }

        public Criteria andSecondguardianWechatBetween(String value1, String value2) {
            addCriterion("secondguardian_wechat between", value1, value2, "secondguardianWechat");
            return (Criteria) this;
        }

        public Criteria andSecondguardianWechatNotBetween(String value1, String value2) {
            addCriterion("secondguardian_wechat not between", value1, value2, "secondguardianWechat");
            return (Criteria) this;
        }

        public Criteria andHealthStateIsNull() {
            addCriterion("health_state is null");
            return (Criteria) this;
        }

        public Criteria andHealthStateIsNotNull() {
            addCriterion("health_state is not null");
            return (Criteria) this;
        }

        public Criteria andHealthStateEqualTo(String value) {
            addCriterion("health_state =", value, "healthState");
            return (Criteria) this;
        }

        public Criteria andHealthStateNotEqualTo(String value) {
            addCriterion("health_state <>", value, "healthState");
            return (Criteria) this;
        }

        public Criteria andHealthStateGreaterThan(String value) {
            addCriterion("health_state >", value, "healthState");
            return (Criteria) this;
        }

        public Criteria andHealthStateGreaterThanOrEqualTo(String value) {
            addCriterion("health_state >=", value, "healthState");
            return (Criteria) this;
        }

        public Criteria andHealthStateLessThan(String value) {
            addCriterion("health_state <", value, "healthState");
            return (Criteria) this;
        }

        public Criteria andHealthStateLessThanOrEqualTo(String value) {
            addCriterion("health_state <=", value, "healthState");
            return (Criteria) this;
        }

        public Criteria andHealthStateLike(String value) {
            addCriterion("health_state like", value, "healthState");
            return (Criteria) this;
        }

        public Criteria andHealthStateNotLike(String value) {
            addCriterion("health_state not like", value, "healthState");
            return (Criteria) this;
        }

        public Criteria andHealthStateIn(List<String> values) {
            addCriterion("health_state in", values, "healthState");
            return (Criteria) this;
        }

        public Criteria andHealthStateNotIn(List<String> values) {
            addCriterion("health_state not in", values, "healthState");
            return (Criteria) this;
        }

        public Criteria andHealthStateBetween(String value1, String value2) {
            addCriterion("health_state between", value1, value2, "healthState");
            return (Criteria) this;
        }

        public Criteria andHealthStateNotBetween(String value1, String value2) {
            addCriterion("health_state not between", value1, value2, "healthState");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("DESCRIPTION is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("DESCRIPTION is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("DESCRIPTION =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("DESCRIPTION <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("DESCRIPTION >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("DESCRIPTION <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("DESCRIPTION like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("DESCRIPTION not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("DESCRIPTION in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("DESCRIPTION not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("DESCRIPTION between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("DESCRIPTION not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andIsactiveIsNull() {
            addCriterion("ISACTIVE is null");
            return (Criteria) this;
        }

        public Criteria andIsactiveIsNotNull() {
            addCriterion("ISACTIVE is not null");
            return (Criteria) this;
        }

        public Criteria andIsactiveEqualTo(String value) {
            addCriterion("ISACTIVE =", value, "isactive");
            return (Criteria) this;
        }

        public Criteria andIsactiveNotEqualTo(String value) {
            addCriterion("ISACTIVE <>", value, "isactive");
            return (Criteria) this;
        }

        public Criteria andIsactiveGreaterThan(String value) {
            addCriterion("ISACTIVE >", value, "isactive");
            return (Criteria) this;
        }

        public Criteria andIsactiveGreaterThanOrEqualTo(String value) {
            addCriterion("ISACTIVE >=", value, "isactive");
            return (Criteria) this;
        }

        public Criteria andIsactiveLessThan(String value) {
            addCriterion("ISACTIVE <", value, "isactive");
            return (Criteria) this;
        }

        public Criteria andIsactiveLessThanOrEqualTo(String value) {
            addCriterion("ISACTIVE <=", value, "isactive");
            return (Criteria) this;
        }

        public Criteria andIsactiveLike(String value) {
            addCriterion("ISACTIVE like", value, "isactive");
            return (Criteria) this;
        }

        public Criteria andIsactiveNotLike(String value) {
            addCriterion("ISACTIVE not like", value, "isactive");
            return (Criteria) this;
        }

        public Criteria andIsactiveIn(List<String> values) {
            addCriterion("ISACTIVE in", values, "isactive");
            return (Criteria) this;
        }

        public Criteria andIsactiveNotIn(List<String> values) {
            addCriterion("ISACTIVE not in", values, "isactive");
            return (Criteria) this;
        }

        public Criteria andIsactiveBetween(String value1, String value2) {
            addCriterion("ISACTIVE between", value1, value2, "isactive");
            return (Criteria) this;
        }

        public Criteria andIsactiveNotBetween(String value1, String value2) {
            addCriterion("ISACTIVE not between", value1, value2, "isactive");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNull() {
            addCriterion("CREATED is null");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNotNull() {
            addCriterion("CREATED is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedEqualTo(Date value) {
            addCriterion("CREATED =", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotEqualTo(Date value) {
            addCriterion("CREATED <>", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThan(Date value) {
            addCriterion("CREATED >", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATED >=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThan(Date value) {
            addCriterion("CREATED <", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThanOrEqualTo(Date value) {
            addCriterion("CREATED <=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedIn(List<Date> values) {
            addCriterion("CREATED in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotIn(List<Date> values) {
            addCriterion("CREATED not in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedBetween(Date value1, Date value2) {
            addCriterion("CREATED between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotBetween(Date value1, Date value2) {
            addCriterion("CREATED not between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andCreatebyIsNull() {
            addCriterion("CREATEBY is null");
            return (Criteria) this;
        }

        public Criteria andCreatebyIsNotNull() {
            addCriterion("CREATEBY is not null");
            return (Criteria) this;
        }

        public Criteria andCreatebyEqualTo(Integer value) {
            addCriterion("CREATEBY =", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotEqualTo(Integer value) {
            addCriterion("CREATEBY <>", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyGreaterThan(Integer value) {
            addCriterion("CREATEBY >", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyGreaterThanOrEqualTo(Integer value) {
            addCriterion("CREATEBY >=", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyLessThan(Integer value) {
            addCriterion("CREATEBY <", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyLessThanOrEqualTo(Integer value) {
            addCriterion("CREATEBY <=", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyIn(List<Integer> values) {
            addCriterion("CREATEBY in", values, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotIn(List<Integer> values) {
            addCriterion("CREATEBY not in", values, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyBetween(Integer value1, Integer value2) {
            addCriterion("CREATEBY between", value1, value2, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotBetween(Integer value1, Integer value2) {
            addCriterion("CREATEBY not between", value1, value2, "createby");
            return (Criteria) this;
        }

        public Criteria andUpdatedIsNull() {
            addCriterion("UPDATED is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedIsNotNull() {
            addCriterion("UPDATED is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedEqualTo(Date value) {
            addCriterion("UPDATED =", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedNotEqualTo(Date value) {
            addCriterion("UPDATED <>", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedGreaterThan(Date value) {
            addCriterion("UPDATED >", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATED >=", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedLessThan(Date value) {
            addCriterion("UPDATED <", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedLessThanOrEqualTo(Date value) {
            addCriterion("UPDATED <=", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedIn(List<Date> values) {
            addCriterion("UPDATED in", values, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedNotIn(List<Date> values) {
            addCriterion("UPDATED not in", values, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedBetween(Date value1, Date value2) {
            addCriterion("UPDATED between", value1, value2, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedNotBetween(Date value1, Date value2) {
            addCriterion("UPDATED not between", value1, value2, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatebyIsNull() {
            addCriterion("UPDATEBY is null");
            return (Criteria) this;
        }

        public Criteria andUpdatebyIsNotNull() {
            addCriterion("UPDATEBY is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatebyEqualTo(Integer value) {
            addCriterion("UPDATEBY =", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyNotEqualTo(Integer value) {
            addCriterion("UPDATEBY <>", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyGreaterThan(Integer value) {
            addCriterion("UPDATEBY >", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyGreaterThanOrEqualTo(Integer value) {
            addCriterion("UPDATEBY >=", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyLessThan(Integer value) {
            addCriterion("UPDATEBY <", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyLessThanOrEqualTo(Integer value) {
            addCriterion("UPDATEBY <=", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyIn(List<Integer> values) {
            addCriterion("UPDATEBY in", values, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyNotIn(List<Integer> values) {
            addCriterion("UPDATEBY not in", values, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyBetween(Integer value1, Integer value2) {
            addCriterion("UPDATEBY between", value1, value2, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyNotBetween(Integer value1, Integer value2) {
            addCriterion("UPDATEBY not between", value1, value2, "updateby");
            return (Criteria) this;
        }

        public Criteria andRemoveIsNull() {
            addCriterion("REMOVE is null");
            return (Criteria) this;
        }

        public Criteria andRemoveIsNotNull() {
            addCriterion("REMOVE is not null");
            return (Criteria) this;
        }

        public Criteria andRemoveEqualTo(String value) {
            addCriterion("REMOVE =", value, "remove");
            return (Criteria) this;
        }

        public Criteria andRemoveNotEqualTo(String value) {
            addCriterion("REMOVE <>", value, "remove");
            return (Criteria) this;
        }

        public Criteria andRemoveGreaterThan(String value) {
            addCriterion("REMOVE >", value, "remove");
            return (Criteria) this;
        }

        public Criteria andRemoveGreaterThanOrEqualTo(String value) {
            addCriterion("REMOVE >=", value, "remove");
            return (Criteria) this;
        }

        public Criteria andRemoveLessThan(String value) {
            addCriterion("REMOVE <", value, "remove");
            return (Criteria) this;
        }

        public Criteria andRemoveLessThanOrEqualTo(String value) {
            addCriterion("REMOVE <=", value, "remove");
            return (Criteria) this;
        }

        public Criteria andRemoveLike(String value) {
            addCriterion("REMOVE like", value, "remove");
            return (Criteria) this;
        }

        public Criteria andRemoveNotLike(String value) {
            addCriterion("REMOVE not like", value, "remove");
            return (Criteria) this;
        }

        public Criteria andRemoveIn(List<String> values) {
            addCriterion("REMOVE in", values, "remove");
            return (Criteria) this;
        }

        public Criteria andRemoveNotIn(List<String> values) {
            addCriterion("REMOVE not in", values, "remove");
            return (Criteria) this;
        }

        public Criteria andRemoveBetween(String value1, String value2) {
            addCriterion("REMOVE between", value1, value2, "remove");
            return (Criteria) this;
        }

        public Criteria andRemoveNotBetween(String value1, String value2) {
            addCriterion("REMOVE not between", value1, value2, "remove");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oldperson_info
     *
     * @mbggenerated do_not_delete_during_merge Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oldperson_info
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}