package com.system.po;

import java.util.Date;

public class user {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.ID
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.ORG_ID
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    private Integer orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.CLIENT_ID
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    private Integer clientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.UserName
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.Password
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.REAL_NAME
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.SEX
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.EMAIL
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.PHONE
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.MOBILE
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.DESCRIPTION
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.ISACTIVE
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    private String isactive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.CREATED
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.CREATEBY
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    private Integer createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.UPDATED
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    private Date updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.UPDATEBY
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    private Integer updateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.REMOVE
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    private String remove;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.DATAFILTER
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    private String datafilter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.theme
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    private String theme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.defaultpage
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    private String defaultpage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.logoimage
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    private String logoimage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.qqopenid
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    private String qqopenid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.appversion
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    private String appversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.jsonauth
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    private String jsonauth;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.ID
     *
     * @return the value of sys_user.ID
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.ID
     *
     * @param id the value for sys_user.ID
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.ORG_ID
     *
     * @return the value of sys_user.ORG_ID
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.ORG_ID
     *
     * @param orgId the value for sys_user.ORG_ID
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.CLIENT_ID
     *
     * @return the value of sys_user.CLIENT_ID
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    public Integer getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.CLIENT_ID
     *
     * @param clientId the value for sys_user.CLIENT_ID
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.UserName
     *
     * @return the value of sys_user.UserName
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.UserName
     *
     * @param username the value for sys_user.UserName
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.Password
     *
     * @return the value of sys_user.Password
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.Password
     *
     * @param password the value for sys_user.Password
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.REAL_NAME
     *
     * @return the value of sys_user.REAL_NAME
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.REAL_NAME
     *
     * @param realName the value for sys_user.REAL_NAME
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.SEX
     *
     * @return the value of sys_user.SEX
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.SEX
     *
     * @param sex the value for sys_user.SEX
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.EMAIL
     *
     * @return the value of sys_user.EMAIL
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.EMAIL
     *
     * @param email the value for sys_user.EMAIL
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.PHONE
     *
     * @return the value of sys_user.PHONE
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.PHONE
     *
     * @param phone the value for sys_user.PHONE
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.MOBILE
     *
     * @return the value of sys_user.MOBILE
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.MOBILE
     *
     * @param mobile the value for sys_user.MOBILE
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.DESCRIPTION
     *
     * @return the value of sys_user.DESCRIPTION
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.DESCRIPTION
     *
     * @param description the value for sys_user.DESCRIPTION
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.ISACTIVE
     *
     * @return the value of sys_user.ISACTIVE
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    public String getIsactive() {
        return isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.ISACTIVE
     *
     * @param isactive the value for sys_user.ISACTIVE
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    public void setIsactive(String isactive) {
        this.isactive = isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.CREATED
     *
     * @return the value of sys_user.CREATED
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.CREATED
     *
     * @param created the value for sys_user.CREATED
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.CREATEBY
     *
     * @return the value of sys_user.CREATEBY
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    public Integer getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.CREATEBY
     *
     * @param createby the value for sys_user.CREATEBY
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    public void setCreateby(Integer createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.UPDATED
     *
     * @return the value of sys_user.UPDATED
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.UPDATED
     *
     * @param updated the value for sys_user.UPDATED
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.UPDATEBY
     *
     * @return the value of sys_user.UPDATEBY
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    public Integer getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.UPDATEBY
     *
     * @param updateby the value for sys_user.UPDATEBY
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    public void setUpdateby(Integer updateby) {
        this.updateby = updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.REMOVE
     *
     * @return the value of sys_user.REMOVE
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    public String getRemove() {
        return remove;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.REMOVE
     *
     * @param remove the value for sys_user.REMOVE
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    public void setRemove(String remove) {
        this.remove = remove;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.DATAFILTER
     *
     * @return the value of sys_user.DATAFILTER
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    public String getDatafilter() {
        return datafilter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.DATAFILTER
     *
     * @param datafilter the value for sys_user.DATAFILTER
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    public void setDatafilter(String datafilter) {
        this.datafilter = datafilter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.theme
     *
     * @return the value of sys_user.theme
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    public String getTheme() {
        return theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.theme
     *
     * @param theme the value for sys_user.theme
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    public void setTheme(String theme) {
        this.theme = theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.defaultpage
     *
     * @return the value of sys_user.defaultpage
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    public String getDefaultpage() {
        return defaultpage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.defaultpage
     *
     * @param defaultpage the value for sys_user.defaultpage
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    public void setDefaultpage(String defaultpage) {
        this.defaultpage = defaultpage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.logoimage
     *
     * @return the value of sys_user.logoimage
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    public String getLogoimage() {
        return logoimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.logoimage
     *
     * @param logoimage the value for sys_user.logoimage
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    public void setLogoimage(String logoimage) {
        this.logoimage = logoimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.qqopenid
     *
     * @return the value of sys_user.qqopenid
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    public String getQqopenid() {
        return qqopenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.qqopenid
     *
     * @param qqopenid the value for sys_user.qqopenid
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    public void setQqopenid(String qqopenid) {
        this.qqopenid = qqopenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.appversion
     *
     * @return the value of sys_user.appversion
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    public String getAppversion() {
        return appversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.appversion
     *
     * @param appversion the value for sys_user.appversion
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    public void setAppversion(String appversion) {
        this.appversion = appversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.jsonauth
     *
     * @return the value of sys_user.jsonauth
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    public String getJsonauth() {
        return jsonauth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.jsonauth
     *
     * @param jsonauth the value for sys_user.jsonauth
     *
     * @mbggenerated Mon Jul 06 15:41:33 GMT+08:00 2020
     */
    public void setJsonauth(String jsonauth) {
        this.jsonauth = jsonauth;
    }
}