package com.system.po;

import java.util.Date;

public class volunteer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer_info.id
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer_info.ORG_ID
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    private Integer orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer_info.CLIENT_ID
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    private Integer clientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer_info.name
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer_info.gender
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer_info.phone
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer_info.id_card
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer_info.birthday
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer_info.checkin_date
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    private Date checkinDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer_info.checkout_date
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    private Date checkoutDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer_info.imgset_dir
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    private String imgsetDir;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer_info.profile_photo
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    private String profilePhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer_info.DESCRIPTION
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer_info.ISACTIVE
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    private String isactive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer_info.CREATED
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer_info.CREATEBY
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    private Integer createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer_info.UPDATED
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    private Date updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer_info.UPDATEBY
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    private Integer updateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer_info.REMOVE
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    private String remove;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer_info.id
     *
     * @return the value of volunteer_info.id
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer_info.id
     *
     * @param id the value for volunteer_info.id
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer_info.ORG_ID
     *
     * @return the value of volunteer_info.ORG_ID
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer_info.ORG_ID
     *
     * @param orgId the value for volunteer_info.ORG_ID
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer_info.CLIENT_ID
     *
     * @return the value of volunteer_info.CLIENT_ID
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    public Integer getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer_info.CLIENT_ID
     *
     * @param clientId the value for volunteer_info.CLIENT_ID
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer_info.name
     *
     * @return the value of volunteer_info.name
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer_info.name
     *
     * @param name the value for volunteer_info.name
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer_info.gender
     *
     * @return the value of volunteer_info.gender
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer_info.gender
     *
     * @param gender the value for volunteer_info.gender
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer_info.phone
     *
     * @return the value of volunteer_info.phone
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer_info.phone
     *
     * @param phone the value for volunteer_info.phone
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer_info.id_card
     *
     * @return the value of volunteer_info.id_card
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer_info.id_card
     *
     * @param idCard the value for volunteer_info.id_card
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer_info.birthday
     *
     * @return the value of volunteer_info.birthday
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer_info.birthday
     *
     * @param birthday the value for volunteer_info.birthday
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer_info.checkin_date
     *
     * @return the value of volunteer_info.checkin_date
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    public Date getCheckinDate() {
        return checkinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer_info.checkin_date
     *
     * @param checkinDate the value for volunteer_info.checkin_date
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    public void setCheckinDate(Date checkinDate) {
        this.checkinDate = checkinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer_info.checkout_date
     *
     * @return the value of volunteer_info.checkout_date
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    public Date getCheckoutDate() {
        return checkoutDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer_info.checkout_date
     *
     * @param checkoutDate the value for volunteer_info.checkout_date
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    public void setCheckoutDate(Date checkoutDate) {
        this.checkoutDate = checkoutDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer_info.imgset_dir
     *
     * @return the value of volunteer_info.imgset_dir
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    public String getImgsetDir() {
        return imgsetDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer_info.imgset_dir
     *
     * @param imgsetDir the value for volunteer_info.imgset_dir
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    public void setImgsetDir(String imgsetDir) {
        this.imgsetDir = imgsetDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer_info.profile_photo
     *
     * @return the value of volunteer_info.profile_photo
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    public String getProfilePhoto() {
        return profilePhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer_info.profile_photo
     *
     * @param profilePhoto the value for volunteer_info.profile_photo
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    public void setProfilePhoto(String profilePhoto) {
        this.profilePhoto = profilePhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer_info.DESCRIPTION
     *
     * @return the value of volunteer_info.DESCRIPTION
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer_info.DESCRIPTION
     *
     * @param description the value for volunteer_info.DESCRIPTION
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer_info.ISACTIVE
     *
     * @return the value of volunteer_info.ISACTIVE
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    public String getIsactive() {
        return isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer_info.ISACTIVE
     *
     * @param isactive the value for volunteer_info.ISACTIVE
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    public void setIsactive(String isactive) {
        this.isactive = isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer_info.CREATED
     *
     * @return the value of volunteer_info.CREATED
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer_info.CREATED
     *
     * @param created the value for volunteer_info.CREATED
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer_info.CREATEBY
     *
     * @return the value of volunteer_info.CREATEBY
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    public Integer getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer_info.CREATEBY
     *
     * @param createby the value for volunteer_info.CREATEBY
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    public void setCreateby(Integer createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer_info.UPDATED
     *
     * @return the value of volunteer_info.UPDATED
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer_info.UPDATED
     *
     * @param updated the value for volunteer_info.UPDATED
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer_info.UPDATEBY
     *
     * @return the value of volunteer_info.UPDATEBY
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    public Integer getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer_info.UPDATEBY
     *
     * @param updateby the value for volunteer_info.UPDATEBY
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    public void setUpdateby(Integer updateby) {
        this.updateby = updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer_info.REMOVE
     *
     * @return the value of volunteer_info.REMOVE
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    public String getRemove() {
        return remove;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer_info.REMOVE
     *
     * @param remove the value for volunteer_info.REMOVE
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    public void setRemove(String remove) {
        this.remove = remove;
    }
}