package com.system.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface employeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    int countByExample(com.system.po.employeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    int deleteByExample(com.system.po.employeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    int insert(com.system.po.employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    int insertSelective(com.system.po.employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    List<com.system.po.employee> selectByExample(com.system.po.employeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    com.system.po.employee selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") com.system.po.employee record, @Param("example") com.system.po.employeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    int updateByExample(@Param("record") com.system.po.employee record, @Param("example") com.system.po.employeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(com.system.po.employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated Tue Jul 07 08:21:24 GMT+08:00 2020
     */
    int updateByPrimaryKey(com.system.po.employee record);
}