package com.system.mapper;

import java.util.List;

import com.system.po.PagingVO;
import org.apache.ibatis.annotations.Param;
import com.system.po.oldperson;
import com.system.po.oldpersonExample;

public interface oldpersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oldperson_info
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    int countByExample(oldpersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oldperson_info
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    int deleteByExample(oldpersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oldperson_info
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oldperson_info
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    int insert(oldperson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oldperson_info
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    int insertSelective(oldperson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oldperson_info
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    List<oldperson> selectByExample(oldpersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oldperson_info
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    oldperson selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oldperson_info
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") oldperson record, @Param("example") oldpersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oldperson_info
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    int updateByExample(@Param("record") oldperson record, @Param("example") oldpersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oldperson_info
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(oldperson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oldperson_info
     *
     * @mbggenerated Mon Jul 06 15:41:19 GMT+08:00 2020
     */
    int updateByPrimaryKey(oldperson record);
}