package com.system.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.system.po.volunteer;
import com.system.po.volunteerExample;

public interface volunteerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_info
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    int countByExample(volunteerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_info
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    int deleteByExample(volunteerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_info
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_info
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    int insert(volunteer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_info
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    int insertSelective(volunteer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_info
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    List<volunteer> selectByExample(volunteerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_info
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    volunteer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_info
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") volunteer record, @Param("example") volunteerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_info
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    int updateByExample(@Param("record") volunteer record, @Param("example") volunteerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_info
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(volunteer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_info
     *
     * @mbggenerated Mon Jul 06 15:41:58 GMT+08:00 2020
     */
    int updateByPrimaryKey(volunteer record);
}